---
version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - restore_cache:
          keys:
          - deps-{{ checksum "Gopkg.lock" }}
          - deps-
      - save_cache:
          paths:
            - ./vendor
          key: deps-{{ checksum "Gopkg.lock" }}
      - run: make test
    working_directory: /go/src/github.com/appvia/hub-quay-agent

  build:
    docker:
      - image: circleci/golang:1.11
    requires:
      - test
    steps:
      - checkout
      - run: make build
    working_directory: /go/src/github.com/appvia/hub-quay-agent

workflows:
  version: 2
  workflow:
    jobs:
    - test
    - build
