// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright (C) 2019  Rohith Jayawardene <gambol99@gmail.com>
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
//

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/appvia/hub-quay-agent/pkg/transport/models"
)

// DeleteTeamsNamespaceNameOKCode is the HTTP code returned for type DeleteTeamsNamespaceNameOK
const DeleteTeamsNamespaceNameOKCode int = 200

/*DeleteTeamsNamespaceNameOK Successfully deleted the team from the organization

swagger:response deleteTeamsNamespaceNameOK
*/
type DeleteTeamsNamespaceNameOK struct {
}

// NewDeleteTeamsNamespaceNameOK creates DeleteTeamsNamespaceNameOK with default headers values
func NewDeleteTeamsNamespaceNameOK() *DeleteTeamsNamespaceNameOK {

	return &DeleteTeamsNamespaceNameOK{}
}

// WriteResponse to the client
func (o *DeleteTeamsNamespaceNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(200)
}

/*DeleteTeamsNamespaceNameDefault A generic erorr returned by the api

swagger:response deleteTeamsNamespaceNameDefault
*/
type DeleteTeamsNamespaceNameDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewDeleteTeamsNamespaceNameDefault creates DeleteTeamsNamespaceNameDefault with default headers values
func NewDeleteTeamsNamespaceNameDefault(code int) *DeleteTeamsNamespaceNameDefault {
	if code <= 0 {
		code = 500
	}

	return &DeleteTeamsNamespaceNameDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the delete teams namespace name default response
func (o *DeleteTeamsNamespaceNameDefault) WithStatusCode(code int) *DeleteTeamsNamespaceNameDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the delete teams namespace name default response
func (o *DeleteTeamsNamespaceNameDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the delete teams namespace name default response
func (o *DeleteTeamsNamespaceNameDefault) WithPayload(payload *models.APIError) *DeleteTeamsNamespaceNameDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the delete teams namespace name default response
func (o *DeleteTeamsNamespaceNameDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *DeleteTeamsNamespaceNameDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
