// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright (C) 2019  Rohith Jayawardene <gambol99@gmail.com>
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
//

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/appvia/hub-quay-agent/pkg/transport/models"
)

// GetTeamsNamespaceOKCode is the HTTP code returned for type GetTeamsNamespaceOK
const GetTeamsNamespaceOKCode int = 200

/*GetTeamsNamespaceOK A collection teams found in the organization

swagger:response getTeamsNamespaceOK
*/
type GetTeamsNamespaceOK struct {

	/*
	  In: Body
	*/
	Payload *models.TeamList `json:"body,omitempty"`
}

// NewGetTeamsNamespaceOK creates GetTeamsNamespaceOK with default headers values
func NewGetTeamsNamespaceOK() *GetTeamsNamespaceOK {

	return &GetTeamsNamespaceOK{}
}

// WithPayload adds the payload to the get teams namespace o k response
func (o *GetTeamsNamespaceOK) WithPayload(payload *models.TeamList) *GetTeamsNamespaceOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get teams namespace o k response
func (o *GetTeamsNamespaceOK) SetPayload(payload *models.TeamList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTeamsNamespaceOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetTeamsNamespaceDefault A generic erorr returned by the api

swagger:response getTeamsNamespaceDefault
*/
type GetTeamsNamespaceDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewGetTeamsNamespaceDefault creates GetTeamsNamespaceDefault with default headers values
func NewGetTeamsNamespaceDefault(code int) *GetTeamsNamespaceDefault {
	if code <= 0 {
		code = 500
	}

	return &GetTeamsNamespaceDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get teams namespace default response
func (o *GetTeamsNamespaceDefault) WithStatusCode(code int) *GetTeamsNamespaceDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get teams namespace default response
func (o *GetTeamsNamespaceDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get teams namespace default response
func (o *GetTeamsNamespaceDefault) WithPayload(payload *models.APIError) *GetTeamsNamespaceDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get teams namespace default response
func (o *GetTeamsNamespaceDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTeamsNamespaceDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
