// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright (C) 2019  Rohith Jayawardene <gambol99@gmail.com>
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
//

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/appvia/hub-quay-agent/pkg/transport/models"
)

// GetTeamsNamespaceNameOKCode is the HTTP code returned for type GetTeamsNamespaceNameOK
const GetTeamsNamespaceNameOKCode int = 200

/*GetTeamsNamespaceNameOK The specification of a team in the organization

swagger:response getTeamsNamespaceNameOK
*/
type GetTeamsNamespaceNameOK struct {

	/*
	  In: Body
	*/
	Payload *models.Team `json:"body,omitempty"`
}

// NewGetTeamsNamespaceNameOK creates GetTeamsNamespaceNameOK with default headers values
func NewGetTeamsNamespaceNameOK() *GetTeamsNamespaceNameOK {

	return &GetTeamsNamespaceNameOK{}
}

// WithPayload adds the payload to the get teams namespace name o k response
func (o *GetTeamsNamespaceNameOK) WithPayload(payload *models.Team) *GetTeamsNamespaceNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get teams namespace name o k response
func (o *GetTeamsNamespaceNameOK) SetPayload(payload *models.Team) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTeamsNamespaceNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetTeamsNamespaceNameDefault A generic erorr returned by the api

swagger:response getTeamsNamespaceNameDefault
*/
type GetTeamsNamespaceNameDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewGetTeamsNamespaceNameDefault creates GetTeamsNamespaceNameDefault with default headers values
func NewGetTeamsNamespaceNameDefault(code int) *GetTeamsNamespaceNameDefault {
	if code <= 0 {
		code = 500
	}

	return &GetTeamsNamespaceNameDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get teams namespace name default response
func (o *GetTeamsNamespaceNameDefault) WithStatusCode(code int) *GetTeamsNamespaceNameDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get teams namespace name default response
func (o *GetTeamsNamespaceNameDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get teams namespace name default response
func (o *GetTeamsNamespaceNameDefault) WithPayload(payload *models.APIError) *GetTeamsNamespaceNameDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get teams namespace name default response
func (o *GetTeamsNamespaceNameDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetTeamsNamespaceNameDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
