// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright (C) 2019  Rohith Jayawardene <gambol99@gmail.com>
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
//

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// GetAliveHandlerFunc turns a function with the right signature into a get alive handler
type GetAliveHandlerFunc func(GetAliveParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetAliveHandlerFunc) Handle(params GetAliveParams) middleware.Responder {
	return fn(params)
}

// GetAliveHandler interface for that can handle valid get alive params
type GetAliveHandler interface {
	Handle(GetAliveParams) middleware.Responder
}

// NewGetAlive creates a new http.Handler for the get alive operation
func NewGetAlive(ctx *middleware.Context, handler GetAliveHandler) *GetAlive {
	return &GetAlive{Context: ctx, Handler: handler}
}

/*GetAlive swagger:route GET /alive getAlive

Get health of Agent

Returns health and status information of the API daemon and
related components such as the runtime.


*/
type GetAlive struct {
	Context *middleware.Context
	Handler GetAliveHandler
}

func (o *GetAlive) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewGetAliveParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
