// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright (C) 2019  Rohith Jayawardene <gambol99@gmail.com>
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
//

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/appvia/hub-quay-agent/pkg/transport/models"
)

// GetRobotsNamespaceNameOKCode is the HTTP code returned for type GetRobotsNamespaceNameOK
const GetRobotsNamespaceNameOKCode int = 200

/*GetRobotsNamespaceNameOK Returning the status of a robot account

swagger:response getRobotsNamespaceNameOK
*/
type GetRobotsNamespaceNameOK struct {

	/*
	  In: Body
	*/
	Payload *models.Robot `json:"body,omitempty"`
}

// NewGetRobotsNamespaceNameOK creates GetRobotsNamespaceNameOK with default headers values
func NewGetRobotsNamespaceNameOK() *GetRobotsNamespaceNameOK {

	return &GetRobotsNamespaceNameOK{}
}

// WithPayload adds the payload to the get robots namespace name o k response
func (o *GetRobotsNamespaceNameOK) WithPayload(payload *models.Robot) *GetRobotsNamespaceNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get robots namespace name o k response
func (o *GetRobotsNamespaceNameOK) SetPayload(payload *models.Robot) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRobotsNamespaceNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetRobotsNamespaceNameNotFoundCode is the HTTP code returned for type GetRobotsNamespaceNameNotFound
const GetRobotsNamespaceNameNotFoundCode int = 404

/*GetRobotsNamespaceNameNotFound A generic erorr returned by the api

swagger:response getRobotsNamespaceNameNotFound
*/
type GetRobotsNamespaceNameNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewGetRobotsNamespaceNameNotFound creates GetRobotsNamespaceNameNotFound with default headers values
func NewGetRobotsNamespaceNameNotFound() *GetRobotsNamespaceNameNotFound {

	return &GetRobotsNamespaceNameNotFound{}
}

// WithPayload adds the payload to the get robots namespace name not found response
func (o *GetRobotsNamespaceNameNotFound) WithPayload(payload *models.APIError) *GetRobotsNamespaceNameNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get robots namespace name not found response
func (o *GetRobotsNamespaceNameNotFound) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRobotsNamespaceNameNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetRobotsNamespaceNameDefault A generic erorr returned by the api

swagger:response getRobotsNamespaceNameDefault
*/
type GetRobotsNamespaceNameDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewGetRobotsNamespaceNameDefault creates GetRobotsNamespaceNameDefault with default headers values
func NewGetRobotsNamespaceNameDefault(code int) *GetRobotsNamespaceNameDefault {
	if code <= 0 {
		code = 500
	}

	return &GetRobotsNamespaceNameDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get robots namespace name default response
func (o *GetRobotsNamespaceNameDefault) WithStatusCode(code int) *GetRobotsNamespaceNameDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get robots namespace name default response
func (o *GetRobotsNamespaceNameDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get robots namespace name default response
func (o *GetRobotsNamespaceNameDefault) WithPayload(payload *models.APIError) *GetRobotsNamespaceNameDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get robots namespace name default response
func (o *GetRobotsNamespaceNameDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRobotsNamespaceNameDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
