// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright (C) 2019  Rohith Jayawardene <gambol99@gmail.com>
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
//

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/appvia/hub-quay-agent/pkg/transport/models"
)

// GetRegistryNamespaceNameOKCode is the HTTP code returned for type GetRegistryNamespaceNameOK
const GetRegistryNamespaceNameOKCode int = 200

/*GetRegistryNamespaceNameOK The specification of a repository in the registry

swagger:response getRegistryNamespaceNameOK
*/
type GetRegistryNamespaceNameOK struct {

	/*
	  In: Body
	*/
	Payload *models.Repository `json:"body,omitempty"`
}

// NewGetRegistryNamespaceNameOK creates GetRegistryNamespaceNameOK with default headers values
func NewGetRegistryNamespaceNameOK() *GetRegistryNamespaceNameOK {

	return &GetRegistryNamespaceNameOK{}
}

// WithPayload adds the payload to the get registry namespace name o k response
func (o *GetRegistryNamespaceNameOK) WithPayload(payload *models.Repository) *GetRegistryNamespaceNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get registry namespace name o k response
func (o *GetRegistryNamespaceNameOK) SetPayload(payload *models.Repository) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRegistryNamespaceNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetRegistryNamespaceNameNotFoundCode is the HTTP code returned for type GetRegistryNamespaceNameNotFound
const GetRegistryNamespaceNameNotFoundCode int = 404

/*GetRegistryNamespaceNameNotFound A generic erorr returned by the api

swagger:response getRegistryNamespaceNameNotFound
*/
type GetRegistryNamespaceNameNotFound struct {

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewGetRegistryNamespaceNameNotFound creates GetRegistryNamespaceNameNotFound with default headers values
func NewGetRegistryNamespaceNameNotFound() *GetRegistryNamespaceNameNotFound {

	return &GetRegistryNamespaceNameNotFound{}
}

// WithPayload adds the payload to the get registry namespace name not found response
func (o *GetRegistryNamespaceNameNotFound) WithPayload(payload *models.APIError) *GetRegistryNamespaceNameNotFound {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get registry namespace name not found response
func (o *GetRegistryNamespaceNameNotFound) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRegistryNamespaceNameNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(404)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetRegistryNamespaceNameDefault A generic erorr returned by the api

swagger:response getRegistryNamespaceNameDefault
*/
type GetRegistryNamespaceNameDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewGetRegistryNamespaceNameDefault creates GetRegistryNamespaceNameDefault with default headers values
func NewGetRegistryNamespaceNameDefault(code int) *GetRegistryNamespaceNameDefault {
	if code <= 0 {
		code = 500
	}

	return &GetRegistryNamespaceNameDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get registry namespace name default response
func (o *GetRegistryNamespaceNameDefault) WithStatusCode(code int) *GetRegistryNamespaceNameDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get registry namespace name default response
func (o *GetRegistryNamespaceNameDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get registry namespace name default response
func (o *GetRegistryNamespaceNameDefault) WithPayload(payload *models.APIError) *GetRegistryNamespaceNameDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get registry namespace name default response
func (o *GetRegistryNamespaceNameDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRegistryNamespaceNameDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
