// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright (C) 2019  Rohith Jayawardene <gambol99@gmail.com>
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
//

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/appvia/hub-quay-agent/pkg/transport/models"
)

// GetRegistryNamespaceNameStatusOKCode is the HTTP code returned for type GetRegistryNamespaceNameStatusOK
const GetRegistryNamespaceNameStatusOKCode int = 200

/*GetRegistryNamespaceNameStatusOK The image analysis of the tags

swagger:response getRegistryNamespaceNameStatusOK
*/
type GetRegistryNamespaceNameStatusOK struct {

	/*
	  In: Body
	*/
	Payload *models.ImageAnalysisList `json:"body,omitempty"`
}

// NewGetRegistryNamespaceNameStatusOK creates GetRegistryNamespaceNameStatusOK with default headers values
func NewGetRegistryNamespaceNameStatusOK() *GetRegistryNamespaceNameStatusOK {

	return &GetRegistryNamespaceNameStatusOK{}
}

// WithPayload adds the payload to the get registry namespace name status o k response
func (o *GetRegistryNamespaceNameStatusOK) WithPayload(payload *models.ImageAnalysisList) *GetRegistryNamespaceNameStatusOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get registry namespace name status o k response
func (o *GetRegistryNamespaceNameStatusOK) SetPayload(payload *models.ImageAnalysisList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRegistryNamespaceNameStatusOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*GetRegistryNamespaceNameStatusDefault A generic erorr returned by the api

swagger:response getRegistryNamespaceNameStatusDefault
*/
type GetRegistryNamespaceNameStatusDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewGetRegistryNamespaceNameStatusDefault creates GetRegistryNamespaceNameStatusDefault with default headers values
func NewGetRegistryNamespaceNameStatusDefault(code int) *GetRegistryNamespaceNameStatusDefault {
	if code <= 0 {
		code = 500
	}

	return &GetRegistryNamespaceNameStatusDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get registry namespace name status default response
func (o *GetRegistryNamespaceNameStatusDefault) WithStatusCode(code int) *GetRegistryNamespaceNameStatusDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get registry namespace name status default response
func (o *GetRegistryNamespaceNameStatusDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get registry namespace name status default response
func (o *GetRegistryNamespaceNameStatusDefault) WithPayload(payload *models.APIError) *GetRegistryNamespaceNameStatusDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get registry namespace name status default response
func (o *GetRegistryNamespaceNameStatusDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetRegistryNamespaceNameStatusDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
