// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright (C) 2019  Rohith Jayawardene <gambol99@gmail.com>
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
//

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/appvia/hub-quay-agent/pkg/transport/restapi/operations/health"
)

// NewHubQuayAgentAPI creates a new HubQuayAgent instance
func NewHubQuayAgentAPI(spec *loads.Document) *HubQuayAgentAPI {
	return &HubQuayAgentAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,
		JSONConsumer:        runtime.JSONConsumer(),
		JSONProducer:        runtime.JSONProducer(),
		DeleteRegistryNamespaceNameHandler: DeleteRegistryNamespaceNameHandlerFunc(func(params DeleteRegistryNamespaceNameParams) middleware.Responder {
			return middleware.NotImplemented("operation DeleteRegistryNamespaceName has not yet been implemented")
		}),
		DeleteRobotsNamespaceNameHandler: DeleteRobotsNamespaceNameHandlerFunc(func(params DeleteRobotsNamespaceNameParams) middleware.Responder {
			return middleware.NotImplemented("operation DeleteRobotsNamespaceName has not yet been implemented")
		}),
		HealthGetHealthzHandler: health.GetHealthzHandlerFunc(func(params health.GetHealthzParams) middleware.Responder {
			return middleware.NotImplemented("operation HealthGetHealthz has not yet been implemented")
		}),
		GetRegistryNamespaceHandler: GetRegistryNamespaceHandlerFunc(func(params GetRegistryNamespaceParams) middleware.Responder {
			return middleware.NotImplemented("operation GetRegistryNamespace has not yet been implemented")
		}),
		GetRegistryNamespaceNameHandler: GetRegistryNamespaceNameHandlerFunc(func(params GetRegistryNamespaceNameParams) middleware.Responder {
			return middleware.NotImplemented("operation GetRegistryNamespaceName has not yet been implemented")
		}),
		GetRobotsNamespaceHandler: GetRobotsNamespaceHandlerFunc(func(params GetRobotsNamespaceParams) middleware.Responder {
			return middleware.NotImplemented("operation GetRobotsNamespace has not yet been implemented")
		}),
		GetRobotsNamespaceNameHandler: GetRobotsNamespaceNameHandlerFunc(func(params GetRobotsNamespaceNameParams) middleware.Responder {
			return middleware.NotImplemented("operation GetRobotsNamespaceName has not yet been implemented")
		}),
		PostRegistryNamespaceNameHandler: PostRegistryNamespaceNameHandlerFunc(func(params PostRegistryNamespaceNameParams) middleware.Responder {
			return middleware.NotImplemented("operation PostRegistryNamespaceName has not yet been implemented")
		}),
		PostRobotsNamespaceNameHandler: PostRobotsNamespaceNameHandlerFunc(func(params PostRobotsNamespaceNameParams) middleware.Responder {
			return middleware.NotImplemented("operation PostRobotsNamespaceName has not yet been implemented")
		}),
	}
}

/*HubQuayAgentAPI an agent used to provision and configure repositories in quay */
type HubQuayAgentAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implemention in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// DeleteRegistryNamespaceNameHandler sets the operation handler for the delete registry namespace name operation
	DeleteRegistryNamespaceNameHandler DeleteRegistryNamespaceNameHandler
	// DeleteRobotsNamespaceNameHandler sets the operation handler for the delete robots namespace name operation
	DeleteRobotsNamespaceNameHandler DeleteRobotsNamespaceNameHandler
	// HealthGetHealthzHandler sets the operation handler for the get healthz operation
	HealthGetHealthzHandler health.GetHealthzHandler
	// GetRegistryNamespaceHandler sets the operation handler for the get registry namespace operation
	GetRegistryNamespaceHandler GetRegistryNamespaceHandler
	// GetRegistryNamespaceNameHandler sets the operation handler for the get registry namespace name operation
	GetRegistryNamespaceNameHandler GetRegistryNamespaceNameHandler
	// GetRobotsNamespaceHandler sets the operation handler for the get robots namespace operation
	GetRobotsNamespaceHandler GetRobotsNamespaceHandler
	// GetRobotsNamespaceNameHandler sets the operation handler for the get robots namespace name operation
	GetRobotsNamespaceNameHandler GetRobotsNamespaceNameHandler
	// PostRegistryNamespaceNameHandler sets the operation handler for the post registry namespace name operation
	PostRegistryNamespaceNameHandler PostRegistryNamespaceNameHandler
	// PostRobotsNamespaceNameHandler sets the operation handler for the post robots namespace name operation
	PostRobotsNamespaceNameHandler PostRobotsNamespaceNameHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *HubQuayAgentAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *HubQuayAgentAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *HubQuayAgentAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *HubQuayAgentAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *HubQuayAgentAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *HubQuayAgentAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *HubQuayAgentAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the HubQuayAgentAPI
func (o *HubQuayAgentAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.DeleteRegistryNamespaceNameHandler == nil {
		unregistered = append(unregistered, "DeleteRegistryNamespaceNameHandler")
	}

	if o.DeleteRobotsNamespaceNameHandler == nil {
		unregistered = append(unregistered, "DeleteRobotsNamespaceNameHandler")
	}

	if o.HealthGetHealthzHandler == nil {
		unregistered = append(unregistered, "health.GetHealthzHandler")
	}

	if o.GetRegistryNamespaceHandler == nil {
		unregistered = append(unregistered, "GetRegistryNamespaceHandler")
	}

	if o.GetRegistryNamespaceNameHandler == nil {
		unregistered = append(unregistered, "GetRegistryNamespaceNameHandler")
	}

	if o.GetRobotsNamespaceHandler == nil {
		unregistered = append(unregistered, "GetRobotsNamespaceHandler")
	}

	if o.GetRobotsNamespaceNameHandler == nil {
		unregistered = append(unregistered, "GetRobotsNamespaceNameHandler")
	}

	if o.PostRegistryNamespaceNameHandler == nil {
		unregistered = append(unregistered, "PostRegistryNamespaceNameHandler")
	}

	if o.PostRobotsNamespaceNameHandler == nil {
		unregistered = append(unregistered, "PostRobotsNamespaceNameHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *HubQuayAgentAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *HubQuayAgentAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	return nil

}

// Authorizer returns the registered authorizer
func (o *HubQuayAgentAPI) Authorizer() runtime.Authorizer {

	return nil

}

// ConsumersFor gets the consumers for the specified media types
func (o *HubQuayAgentAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *HubQuayAgentAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *HubQuayAgentAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the hub quay agent API
func (o *HubQuayAgentAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *HubQuayAgentAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/registry/{namespace}/{name}"] = NewDeleteRegistryNamespaceName(o.context, o.DeleteRegistryNamespaceNameHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/robots/{namespace}/{name}"] = NewDeleteRobotsNamespaceName(o.context, o.DeleteRobotsNamespaceNameHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/healthz"] = health.NewGetHealthz(o.context, o.HealthGetHealthzHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/registry/{namespace}"] = NewGetRegistryNamespace(o.context, o.GetRegistryNamespaceHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/registry/{namespace}/{name}"] = NewGetRegistryNamespaceName(o.context, o.GetRegistryNamespaceNameHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/robots/{namespace}"] = NewGetRobotsNamespace(o.context, o.GetRobotsNamespaceHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/robots/{namespace}/{name}"] = NewGetRobotsNamespaceName(o.context, o.GetRobotsNamespaceNameHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/registry/{namespace}/{name}"] = NewPostRegistryNamespaceName(o.context, o.PostRegistryNamespaceNameHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/robots/{namespace}/{name}"] = NewPostRobotsNamespaceName(o.context, o.PostRobotsNamespaceNameHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *HubQuayAgentAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *HubQuayAgentAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *HubQuayAgentAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *HubQuayAgentAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}
