// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright (C) 2019  Rohith Jayawardene <gambol99@gmail.com>
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
//

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/appvia/hub-quay-agent/pkg/transport/models"
)

// PostRegistryNamespaceNameOKCode is the HTTP code returned for type PostRegistryNamespaceNameOK
const PostRegistryNamespaceNameOKCode int = 200

/*PostRegistryNamespaceNameOK The specification of a repository in the registry

swagger:response postRegistryNamespaceNameOK
*/
type PostRegistryNamespaceNameOK struct {

	/*
	  In: Body
	*/
	Payload *models.Repository `json:"body,omitempty"`
}

// NewPostRegistryNamespaceNameOK creates PostRegistryNamespaceNameOK with default headers values
func NewPostRegistryNamespaceNameOK() *PostRegistryNamespaceNameOK {

	return &PostRegistryNamespaceNameOK{}
}

// WithPayload adds the payload to the post registry namespace name o k response
func (o *PostRegistryNamespaceNameOK) WithPayload(payload *models.Repository) *PostRegistryNamespaceNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post registry namespace name o k response
func (o *PostRegistryNamespaceNameOK) SetPayload(payload *models.Repository) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostRegistryNamespaceNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PostRegistryNamespaceNameDefault A generic erorr returned by the api

swagger:response postRegistryNamespaceNameDefault
*/
type PostRegistryNamespaceNameDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewPostRegistryNamespaceNameDefault creates PostRegistryNamespaceNameDefault with default headers values
func NewPostRegistryNamespaceNameDefault(code int) *PostRegistryNamespaceNameDefault {
	if code <= 0 {
		code = 500
	}

	return &PostRegistryNamespaceNameDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the post registry namespace name default response
func (o *PostRegistryNamespaceNameDefault) WithStatusCode(code int) *PostRegistryNamespaceNameDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the post registry namespace name default response
func (o *PostRegistryNamespaceNameDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the post registry namespace name default response
func (o *PostRegistryNamespaceNameDefault) WithPayload(payload *models.APIError) *PostRegistryNamespaceNameDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the post registry namespace name default response
func (o *PostRegistryNamespaceNameDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PostRegistryNamespaceNameDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
