// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright (C) 2019  Rohith Jayawardene <gambol99@gmail.com>
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
//

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/appvia/hub-quay-agent/pkg/transport/models"
)

// PutTeamsNamespaceNameOKCode is the HTTP code returned for type PutTeamsNamespaceNameOK
const PutTeamsNamespaceNameOKCode int = 200

/*PutTeamsNamespaceNameOK The specification of a team in the organization

swagger:response putTeamsNamespaceNameOK
*/
type PutTeamsNamespaceNameOK struct {

	/*
	  In: Body
	*/
	Payload *models.Team `json:"body,omitempty"`
}

// NewPutTeamsNamespaceNameOK creates PutTeamsNamespaceNameOK with default headers values
func NewPutTeamsNamespaceNameOK() *PutTeamsNamespaceNameOK {

	return &PutTeamsNamespaceNameOK{}
}

// WithPayload adds the payload to the put teams namespace name o k response
func (o *PutTeamsNamespaceNameOK) WithPayload(payload *models.Team) *PutTeamsNamespaceNameOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put teams namespace name o k response
func (o *PutTeamsNamespaceNameOK) SetPayload(payload *models.Team) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutTeamsNamespaceNameOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*PutTeamsNamespaceNameDefault A generic erorr returned by the api

swagger:response putTeamsNamespaceNameDefault
*/
type PutTeamsNamespaceNameDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.APIError `json:"body,omitempty"`
}

// NewPutTeamsNamespaceNameDefault creates PutTeamsNamespaceNameDefault with default headers values
func NewPutTeamsNamespaceNameDefault(code int) *PutTeamsNamespaceNameDefault {
	if code <= 0 {
		code = 500
	}

	return &PutTeamsNamespaceNameDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the put teams namespace name default response
func (o *PutTeamsNamespaceNameDefault) WithStatusCode(code int) *PutTeamsNamespaceNameDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the put teams namespace name default response
func (o *PutTeamsNamespaceNameDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the put teams namespace name default response
func (o *PutTeamsNamespaceNameDefault) WithPayload(payload *models.APIError) *PutTeamsNamespaceNameDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the put teams namespace name default response
func (o *PutTeamsNamespaceNameDefault) SetPayload(payload *models.APIError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *PutTeamsNamespaceNameDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
