// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright (C) 2019  Rohith Jayawardene <gambol99@gmail.com>
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
//

/*
Package restapi hub-quay-agent
an agent used to provision and configure repositories in quay


    Schemes:
      http
    Host: localhost
    BasePath: /api/v1beta
    Version: v1beta
    Contact: admin@appvia.io<support@appvia.io> https://github.com/appvia/hub-quay-agent

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
