// Code generated by go-swagger; DO NOT EDIT.

//
// Copyright (C) 2019  Rohith Jayawardene <gambol99@gmail.com>
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <http://www.gnu.org/licenses/>.
//
//

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "an agent used to provision and configure repositories in quay",
    "title": "hub-quay-agent",
    "contact": {
      "name": "admin@appvia.io",
      "url": "https://github.com/appvia/hub-quay-agent",
      "email": "support@appvia.io"
    },
    "version": "v1beta"
  },
  "basePath": "/api/v1beta",
  "paths": {
    "/alive": {
      "get": {
        "security": [],
        "description": "Returns health and status information of the API daemon and related components such as the runtime.\n",
        "summary": "Get health of Agent",
        "responses": {
          "200": {
            "description": "Success"
          },
          "default": {
            "$ref": "#/responses/apierror"
          }
        }
      }
    },
    "/healthz/{namespace}": {
      "get": {
        "description": "Request the agent for validate the health of the agent\n",
        "summary": "Perform an intelligent health check on the agent",
        "parameters": [
          {
            "$ref": "#/parameters/namespace"
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "default": {
            "$ref": "#/responses/apierror"
          }
        }
      }
    },
    "/registry/{namespace}": {
      "get": {
        "description": "Used to retrieve a repository from the registry\n",
        "summary": "Retrieves a list of respositories witin the registry",
        "parameters": [
          {
            "$ref": "#/parameters/namespace"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/repositories"
          },
          "default": {
            "$ref": "#/responses/apierror"
          }
        }
      }
    },
    "/registry/{namespace}/{name}": {
      "get": {
        "description": "Used to retrieve a repository from the registry\n",
        "summary": "Retrieves the configuration of a repository in the registry",
        "parameters": [
          {
            "$ref": "#/parameters/namespace"
          },
          {
            "$ref": "#/parameters/name"
          },
          {
            "$ref": "#/parameters/includeTags"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/repository"
          },
          "404": {
            "$ref": "#/responses/apierror"
          },
          "default": {
            "$ref": "#/responses/apierror"
          }
        }
      },
      "put": {
        "description": "Used to create a new repository or update a repository in the registry\n",
        "summary": "Create a new repository within Quay",
        "parameters": [
          {
            "$ref": "#/parameters/namespace"
          },
          {
            "$ref": "#/parameters/name"
          },
          {
            "$ref": "#/parameters/repository"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/repository"
          },
          "default": {
            "$ref": "#/responses/apierror"
          }
        }
      },
      "delete": {
        "description": "Deletes the repository, the associated user policy and all images associated\n",
        "summary": "Responsible for deleting a repository",
        "parameters": [
          {
            "$ref": "#/parameters/namespace"
          },
          {
            "$ref": "#/parameters/name"
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully deleted the repository from the organization"
          },
          "default": {
            "$ref": "#/responses/apierror"
          }
        }
      }
    },
    "/registry/{namespace}/{name}/status": {
      "get": {
        "description": "Used to retrieve security assessment of the image and tags\n",
        "summary": "Retrieves the security assessment of the image tags",
        "parameters": [
          {
            "$ref": "#/parameters/namespace"
          },
          {
            "$ref": "#/parameters/name"
          },
          {
            "$ref": "#/parameters/tag"
          },
          {
            "$ref": "#/parameters/limit"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/analysis"
          },
          "default": {
            "$ref": "#/responses/apierror"
          }
        }
      }
    },
    "/robots/{namespace}": {
      "get": {
        "description": "Used to retrieve a list of robot accounts and the permissions they have on the repositories\n",
        "summary": "Retrieves a list of robot accounts from within the registry",
        "parameters": [
          {
            "$ref": "#/parameters/namespace"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/robots"
          },
          "default": {
            "$ref": "#/responses/apierror"
          }
        }
      }
    },
    "/robots/{namespace}/{name}": {
      "get": {
        "description": "Used to retrieve a list of robot accounts and the permissions they have on the repositories\n",
        "summary": "Retrieves a list of robot accounts from within the registry",
        "parameters": [
          {
            "$ref": "#/parameters/namespace"
          },
          {
            "$ref": "#/parameters/name"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/robot"
          },
          "404": {
            "$ref": "#/responses/apierror"
          },
          "default": {
            "$ref": "#/responses/apierror"
          }
        }
      },
      "put": {
        "description": "Used to retrieve a list of robot accounts and the permissions they have on the repositories\n",
        "summary": "Retrieves a list of robot accounts from within the registry",
        "parameters": [
          {
            "$ref": "#/parameters/namespace"
          },
          {
            "$ref": "#/parameters/name"
          },
          {
            "$ref": "#/parameters/robot"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/robot"
          },
          "default": {
            "$ref": "#/responses/apierror"
          }
        }
      },
      "delete": {
        "description": "Used to delete a robot account and all permissions from a robot account\n",
        "summary": "Deletes a robot account from the organization",
        "parameters": [
          {
            "$ref": "#/parameters/namespace"
          },
          {
            "$ref": "#/parameters/name"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/robot"
          },
          "default": {
            "$ref": "#/responses/apierror"
          }
        }
      }
    },
    "/teams/{namespace}": {
      "get": {
        "description": "Used to retrieve a complete list of all teams in the organization\n",
        "summary": "Retrieves a list of teams in the organization",
        "parameters": [
          {
            "$ref": "#/parameters/namespace"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/teams"
          },
          "default": {
            "$ref": "#/responses/apierror"
          }
        }
      }
    },
    "/teams/{namespace}/{name}": {
      "get": {
        "description": "Used to retrieve the team resource from Quay\n",
        "summary": "Retrieves the team resource",
        "parameters": [
          {
            "$ref": "#/parameters/namespace"
          },
          {
            "$ref": "#/parameters/name"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/team"
          },
          "default": {
            "$ref": "#/responses/apierror"
          }
        }
      },
      "put": {
        "description": "Used to perform updates or creations of teams in Quay\n",
        "summary": "Update the team membership",
        "parameters": [
          {
            "$ref": "#/parameters/namespace"
          },
          {
            "$ref": "#/parameters/name"
          },
          {
            "$ref": "#/parameters/team"
          }
        ],
        "responses": {
          "200": {
            "$ref": "#/responses/team"
          },
          "default": {
            "$ref": "#/responses/apierror"
          }
        }
      },
      "delete": {
        "description": "Used to delete a team from Quay\n",
        "summary": "Delete a team from Quay",
        "parameters": [
          {
            "$ref": "#/parameters/namespace"
          },
          {
            "$ref": "#/parameters/name"
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully deleted the team from the organization"
          },
          "default": {
            "$ref": "#/responses/apierror"
          }
        }
      }
    }
  },
  "definitions": {
    "APIError": {
      "description": "Is a generic error event returned when the we have an internal error\n",
      "type": "object",
      "required": [
        "reason"
      ],
      "properties": {
        "detail": {
          "description": "Additional details related to the error",
          "type": "string"
        },
        "reason": {
          "description": "A human readable description used to define what error has occured\n",
          "type": "string"
        }
      }
    },
    "ImageAnalysis": {
      "description": "The resource definition for a list of vulnerabilities on a image tag\n",
      "type": "object",
      "required": [
        "spec"
      ],
      "allOf": [
        {
          "$ref": "#/definitions/Object"
        }
      ],
      "properties": {
        "spec": {
          "$ref": "#/definitions/ImageAnalysisSpec"
        }
      }
    },
    "ImageAnalysisList": {
      "description": "The resource definition for the results of a image scan on a",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/Object"
        }
      ],
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ImageAnalysis"
          }
        }
      }
    },
    "ImageAnalysisSpec": {
      "description": "The resource specification for a image analysis\n",
      "required": [
        "status",
        "tag"
      ],
      "properties": {
        "features": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ImageFeature"
          }
        },
        "namespace": {
          "description": "The namespace catagory for the layer",
          "type": "string"
        },
        "status": {
          "description": "The status of the image analysis, which can be queued or scanned\n",
          "enum": [
            "scanned",
            "queued"
          ]
        },
        "tag": {
          "$ref": "#/definitions/RepositoryTag"
        }
      }
    },
    "ImageFeature": {
      "description": "A layer feature within the image",
      "type": "object",
      "required": [
        "addedby",
        "format",
        "name",
        "namespace",
        "version"
      ],
      "properties": {
        "addedby": {
          "description": "The layer the feature was added",
          "type": "string"
        },
        "format": {
          "description": "The format of the feature being added",
          "type": "string"
        },
        "name": {
          "description": "The name of the feature which is being added",
          "type": "string"
        },
        "namespace": {
          "description": "An associated namespace to describe the feature",
          "type": "string"
        },
        "version": {
          "description": "An associated version to the feature being added",
          "type": "string"
        },
        "vulnerabilities": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ImageVulnerability"
          }
        }
      }
    },
    "ImageVulnerability": {
      "description": "Defines the structure for a image vulnerability",
      "type": "object",
      "required": [
        "link",
        "name",
        "severity"
      ],
      "properties": {
        "fixedby": {
          "description": "A potential link or information related to a fix",
          "type": "string"
        },
        "link": {
          "description": "A hyperlink to details on the vulnerability",
          "type": "string"
        },
        "name": {
          "description": "The name of the vulnerability",
          "type": "string"
        },
        "namespace": {
          "description": "The namespace catagory for this vulnerability",
          "type": "string"
        },
        "severity": {
          "description": "The severity severity of the vulnerability",
          "type": "string"
        }
      }
    },
    "Object": {
      "description": "The definition of a object",
      "type": "object",
      "required": [
        "name",
        "namespace"
      ],
      "properties": {
        "name": {
          "description": "A globally unique human readible resource name",
          "type": "string"
        },
        "namespace": {
          "description": "A namespace for the resource, which in this case maps on the organization\n",
          "type": "string"
        }
      }
    },
    "Permission": {
      "description": "Is the definition for a permission on a repository",
      "type": "object",
      "required": [
        "name",
        "permission"
      ],
      "properties": {
        "name": {
          "description": "The identifier for the identity applying the permission to",
          "type": "string"
        },
        "permission": {
          "description": "The level of access to be given to the identify (team, member or robot)\n",
          "type": "string",
          "enum": [
            "admin",
            "none",
            "read",
            "write"
          ]
        }
      }
    },
    "Principal": {
      "type": "string"
    },
    "Repository": {
      "description": "The resource definition for a repository in the registry",
      "type": "object",
      "required": [
        "spec"
      ],
      "allOf": [
        {
          "$ref": "#/definitions/Object"
        }
      ],
      "properties": {
        "spec": {
          "$ref": "#/definitions/RepositorySpec"
        }
      }
    },
    "RepositoryList": {
      "description": "A list of repositories found",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/Object"
        }
      ],
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Repository"
          }
        }
      }
    },
    "RepositorySpec": {
      "description": "The definitions for a repository",
      "type": "object",
      "required": [
        "visibility"
      ],
      "properties": {
        "description": {
          "description": "A description about what the image is used for",
          "type": "string"
        },
        "members": {
          "description": "A list of members whom has access to the repository",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Permission"
          }
        },
        "robots": {
          "description": "A list of robot accounts who access to the repository",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Permission"
          }
        },
        "tags": {
          "description": "A collection of tags associated to the image",
          "type": "array",
          "items": {
            "$ref": "#/definitions/RepositoryTag"
          }
        },
        "teams": {
          "description": "A list of teams which have access to the repository",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Permission"
          }
        },
        "url": {
          "description": "The docker pull url for this image",
          "type": "string"
        },
        "visibility": {
          "description": "The visibility of the repository in the registry",
          "type": "string",
          "enum": [
            "internal",
            "private",
            "public"
          ]
        }
      }
    },
    "RepositoryTag": {
      "description": "The definition for a repository image tag",
      "type": "object",
      "required": [
        "digest",
        "imageId",
        "last_modified",
        "name"
      ],
      "properties": {
        "digest": {
          "description": "Is the image digest for this image",
          "type": "string"
        },
        "imageId": {
          "description": "Is the image id for this image tag",
          "type": "string"
        },
        "last_modified": {
          "description": "The last time the tags was modified",
          "type": "string"
        },
        "name": {
          "description": "Is the image tag name i.e. latest, v0.0.1 etc",
          "type": "string"
        },
        "size": {
          "description": "The size of the image in the repository",
          "type": "integer"
        }
      }
    },
    "Robot": {
      "description": "The resource definition for a robot account",
      "type": "object",
      "required": [
        "spec"
      ],
      "allOf": [
        {
          "$ref": "#/definitions/Object"
        }
      ],
      "properties": {
        "spec": {
          "$ref": "#/definitions/RobotSpec"
        }
      }
    },
    "RobotList": {
      "description": "A list of robot accounts",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/Object"
        }
      ],
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Robot"
          }
        }
      }
    },
    "RobotSpec": {
      "description": "The resource specification of a robot account",
      "type": "object",
      "required": [
        "description"
      ],
      "properties": {
        "description": {
          "description": "A summary of what the robot account is for",
          "type": "string"
        },
        "password": {
          "description": "The password associated to the robot account",
          "type": "string"
        },
        "tags": {
          "description": "A collection of tags associated to the robot account",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "token": {
          "description": "The token associated to the the robot account",
          "type": "string"
        },
        "username": {
          "description": "The username associated to the robot account",
          "type": "string"
        }
      }
    },
    "Team": {
      "description": "Is the team resources i.e collection of members",
      "type": "object",
      "required": [
        "spec"
      ],
      "allOf": [
        {
          "$ref": "#/definitions/Object"
        }
      ],
      "properties": {
        "spec": {
          "$ref": "#/definitions/TeamSpec"
        }
      }
    },
    "TeamList": {
      "description": "A collection of teams in the organization",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/Object"
        }
      ],
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Team"
          }
        }
      }
    },
    "TeamSpec": {
      "description": "Is the specification of the configuration of the resource",
      "type": "object",
      "properties": {
        "members": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  },
  "parameters": {
    "authinfo": {
      "type": "string",
      "description": "An authentication context to speak to the backend of behalf of the Hub\n",
      "name": "X-AuthInfo",
      "in": "header"
    },
    "includeTags": {
      "type": "boolean",
      "description": "Indicates we should include tags in the repositories\n",
      "name": "includeTags",
      "in": "query"
    },
    "limit": {
      "type": "integer",
      "default": 5,
      "description": "Used to limit the results of a query\n",
      "name": "limit",
      "in": "query"
    },
    "name": {
      "type": "string",
      "description": "The name of the repository you are acting upon\n",
      "name": "name",
      "in": "path",
      "required": true
    },
    "namespace": {
      "type": "string",
      "description": "The namespace of the repository\n",
      "name": "namespace",
      "in": "path",
      "required": true
    },
    "repository": {
      "description": "The repository definition we are acting on\n",
      "name": "repository",
      "in": "body",
      "required": true,
      "schema": {
        "$ref": "#/definitions/Repository"
      }
    },
    "robot": {
      "description": "The definition of a robot account within the registry\n",
      "name": "robot",
      "in": "body",
      "required": true,
      "schema": {
        "$ref": "#/definitions/Robot"
      }
    },
    "tag": {
      "type": "string",
      "description": "Used to specify a specific image tag\n",
      "name": "tag",
      "in": "query"
    },
    "team": {
      "description": "The definition of a team within the organization\n",
      "name": "team",
      "in": "body",
      "required": true,
      "schema": {
        "$ref": "#/definitions/Team"
      }
    }
  },
  "responses": {
    "analysis": {
      "description": "The image analysis of the tags",
      "schema": {
        "$ref": "#/definitions/ImageAnalysisList"
      }
    },
    "apierror": {
      "description": "A generic erorr returned by the api",
      "schema": {
        "$ref": "#/definitions/APIError"
      }
    },
    "notfound": {
      "description": "The resource does not exist"
    },
    "repositories": {
      "description": "A collection repositories found in the registry",
      "schema": {
        "$ref": "#/definitions/RepositoryList"
      }
    },
    "repository": {
      "description": "The specification of a repository in the registry",
      "schema": {
        "$ref": "#/definitions/Repository"
      }
    },
    "robot": {
      "description": "Returning the status of a robot account",
      "schema": {
        "$ref": "#/definitions/Robot"
      }
    },
    "robots": {
      "description": "Returning a list of robot accounts",
      "schema": {
        "$ref": "#/definitions/RobotList"
      }
    },
    "team": {
      "description": "The specification of a team in the organization",
      "schema": {
        "$ref": "#/definitions/Team"
      }
    },
    "teams": {
      "description": "A collection teams found in the organization",
      "schema": {
        "$ref": "#/definitions/TeamList"
      }
    }
  },
  "securityDefinitions": {
    "apikey": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "security": [
    {
      "apikey": null
    }
  ]
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "an agent used to provision and configure repositories in quay",
    "title": "hub-quay-agent",
    "contact": {
      "name": "admin@appvia.io",
      "url": "https://github.com/appvia/hub-quay-agent",
      "email": "support@appvia.io"
    },
    "version": "v1beta"
  },
  "basePath": "/api/v1beta",
  "paths": {
    "/alive": {
      "get": {
        "security": [],
        "description": "Returns health and status information of the API daemon and related components such as the runtime.\n",
        "summary": "Get health of Agent",
        "responses": {
          "200": {
            "description": "Success"
          },
          "default": {
            "description": "A generic erorr returned by the api",
            "schema": {
              "$ref": "#/definitions/APIError"
            }
          }
        }
      }
    },
    "/healthz/{namespace}": {
      "get": {
        "description": "Request the agent for validate the health of the agent\n",
        "summary": "Perform an intelligent health check on the agent",
        "parameters": [
          {
            "type": "string",
            "description": "The namespace of the repository\n",
            "name": "namespace",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Success"
          },
          "default": {
            "description": "A generic erorr returned by the api",
            "schema": {
              "$ref": "#/definitions/APIError"
            }
          }
        }
      }
    },
    "/registry/{namespace}": {
      "get": {
        "description": "Used to retrieve a repository from the registry\n",
        "summary": "Retrieves a list of respositories witin the registry",
        "parameters": [
          {
            "type": "string",
            "description": "The namespace of the repository\n",
            "name": "namespace",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A collection repositories found in the registry",
            "schema": {
              "$ref": "#/definitions/RepositoryList"
            }
          },
          "default": {
            "description": "A generic erorr returned by the api",
            "schema": {
              "$ref": "#/definitions/APIError"
            }
          }
        }
      }
    },
    "/registry/{namespace}/{name}": {
      "get": {
        "description": "Used to retrieve a repository from the registry\n",
        "summary": "Retrieves the configuration of a repository in the registry",
        "parameters": [
          {
            "type": "string",
            "description": "The namespace of the repository\n",
            "name": "namespace",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The name of the repository you are acting upon\n",
            "name": "name",
            "in": "path",
            "required": true
          },
          {
            "type": "boolean",
            "description": "Indicates we should include tags in the repositories\n",
            "name": "includeTags",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "The specification of a repository in the registry",
            "schema": {
              "$ref": "#/definitions/Repository"
            }
          },
          "404": {
            "description": "A generic erorr returned by the api",
            "schema": {
              "$ref": "#/definitions/APIError"
            }
          },
          "default": {
            "description": "A generic erorr returned by the api",
            "schema": {
              "$ref": "#/definitions/APIError"
            }
          }
        }
      },
      "put": {
        "description": "Used to create a new repository or update a repository in the registry\n",
        "summary": "Create a new repository within Quay",
        "parameters": [
          {
            "type": "string",
            "description": "The namespace of the repository\n",
            "name": "namespace",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The name of the repository you are acting upon\n",
            "name": "name",
            "in": "path",
            "required": true
          },
          {
            "description": "The repository definition we are acting on\n",
            "name": "repository",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Repository"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The specification of a repository in the registry",
            "schema": {
              "$ref": "#/definitions/Repository"
            }
          },
          "default": {
            "description": "A generic erorr returned by the api",
            "schema": {
              "$ref": "#/definitions/APIError"
            }
          }
        }
      },
      "delete": {
        "description": "Deletes the repository, the associated user policy and all images associated\n",
        "summary": "Responsible for deleting a repository",
        "parameters": [
          {
            "type": "string",
            "description": "The namespace of the repository\n",
            "name": "namespace",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The name of the repository you are acting upon\n",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully deleted the repository from the organization"
          },
          "default": {
            "description": "A generic erorr returned by the api",
            "schema": {
              "$ref": "#/definitions/APIError"
            }
          }
        }
      }
    },
    "/registry/{namespace}/{name}/status": {
      "get": {
        "description": "Used to retrieve security assessment of the image and tags\n",
        "summary": "Retrieves the security assessment of the image tags",
        "parameters": [
          {
            "type": "string",
            "description": "The namespace of the repository\n",
            "name": "namespace",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The name of the repository you are acting upon\n",
            "name": "name",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "Used to specify a specific image tag\n",
            "name": "tag",
            "in": "query"
          },
          {
            "type": "integer",
            "default": 5,
            "description": "Used to limit the results of a query\n",
            "name": "limit",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "The image analysis of the tags",
            "schema": {
              "$ref": "#/definitions/ImageAnalysisList"
            }
          },
          "default": {
            "description": "A generic erorr returned by the api",
            "schema": {
              "$ref": "#/definitions/APIError"
            }
          }
        }
      }
    },
    "/robots/{namespace}": {
      "get": {
        "description": "Used to retrieve a list of robot accounts and the permissions they have on the repositories\n",
        "summary": "Retrieves a list of robot accounts from within the registry",
        "parameters": [
          {
            "type": "string",
            "description": "The namespace of the repository\n",
            "name": "namespace",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returning a list of robot accounts",
            "schema": {
              "$ref": "#/definitions/RobotList"
            }
          },
          "default": {
            "description": "A generic erorr returned by the api",
            "schema": {
              "$ref": "#/definitions/APIError"
            }
          }
        }
      }
    },
    "/robots/{namespace}/{name}": {
      "get": {
        "description": "Used to retrieve a list of robot accounts and the permissions they have on the repositories\n",
        "summary": "Retrieves a list of robot accounts from within the registry",
        "parameters": [
          {
            "type": "string",
            "description": "The namespace of the repository\n",
            "name": "namespace",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The name of the repository you are acting upon\n",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returning the status of a robot account",
            "schema": {
              "$ref": "#/definitions/Robot"
            }
          },
          "404": {
            "description": "A generic erorr returned by the api",
            "schema": {
              "$ref": "#/definitions/APIError"
            }
          },
          "default": {
            "description": "A generic erorr returned by the api",
            "schema": {
              "$ref": "#/definitions/APIError"
            }
          }
        }
      },
      "put": {
        "description": "Used to retrieve a list of robot accounts and the permissions they have on the repositories\n",
        "summary": "Retrieves a list of robot accounts from within the registry",
        "parameters": [
          {
            "type": "string",
            "description": "The namespace of the repository\n",
            "name": "namespace",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The name of the repository you are acting upon\n",
            "name": "name",
            "in": "path",
            "required": true
          },
          {
            "description": "The definition of a robot account within the registry\n",
            "name": "robot",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Robot"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Returning the status of a robot account",
            "schema": {
              "$ref": "#/definitions/Robot"
            }
          },
          "default": {
            "description": "A generic erorr returned by the api",
            "schema": {
              "$ref": "#/definitions/APIError"
            }
          }
        }
      },
      "delete": {
        "description": "Used to delete a robot account and all permissions from a robot account\n",
        "summary": "Deletes a robot account from the organization",
        "parameters": [
          {
            "type": "string",
            "description": "The namespace of the repository\n",
            "name": "namespace",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The name of the repository you are acting upon\n",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returning the status of a robot account",
            "schema": {
              "$ref": "#/definitions/Robot"
            }
          },
          "default": {
            "description": "A generic erorr returned by the api",
            "schema": {
              "$ref": "#/definitions/APIError"
            }
          }
        }
      }
    },
    "/teams/{namespace}": {
      "get": {
        "description": "Used to retrieve a complete list of all teams in the organization\n",
        "summary": "Retrieves a list of teams in the organization",
        "parameters": [
          {
            "type": "string",
            "description": "The namespace of the repository\n",
            "name": "namespace",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "A collection teams found in the organization",
            "schema": {
              "$ref": "#/definitions/TeamList"
            }
          },
          "default": {
            "description": "A generic erorr returned by the api",
            "schema": {
              "$ref": "#/definitions/APIError"
            }
          }
        }
      }
    },
    "/teams/{namespace}/{name}": {
      "get": {
        "description": "Used to retrieve the team resource from Quay\n",
        "summary": "Retrieves the team resource",
        "parameters": [
          {
            "type": "string",
            "description": "The namespace of the repository\n",
            "name": "namespace",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The name of the repository you are acting upon\n",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "The specification of a team in the organization",
            "schema": {
              "$ref": "#/definitions/Team"
            }
          },
          "default": {
            "description": "A generic erorr returned by the api",
            "schema": {
              "$ref": "#/definitions/APIError"
            }
          }
        }
      },
      "put": {
        "description": "Used to perform updates or creations of teams in Quay\n",
        "summary": "Update the team membership",
        "parameters": [
          {
            "type": "string",
            "description": "The namespace of the repository\n",
            "name": "namespace",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The name of the repository you are acting upon\n",
            "name": "name",
            "in": "path",
            "required": true
          },
          {
            "description": "The definition of a team within the organization\n",
            "name": "team",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Team"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "The specification of a team in the organization",
            "schema": {
              "$ref": "#/definitions/Team"
            }
          },
          "default": {
            "description": "A generic erorr returned by the api",
            "schema": {
              "$ref": "#/definitions/APIError"
            }
          }
        }
      },
      "delete": {
        "description": "Used to delete a team from Quay\n",
        "summary": "Delete a team from Quay",
        "parameters": [
          {
            "type": "string",
            "description": "The namespace of the repository\n",
            "name": "namespace",
            "in": "path",
            "required": true
          },
          {
            "type": "string",
            "description": "The name of the repository you are acting upon\n",
            "name": "name",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Successfully deleted the team from the organization"
          },
          "default": {
            "description": "A generic erorr returned by the api",
            "schema": {
              "$ref": "#/definitions/APIError"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "APIError": {
      "description": "Is a generic error event returned when the we have an internal error\n",
      "type": "object",
      "required": [
        "reason"
      ],
      "properties": {
        "detail": {
          "description": "Additional details related to the error",
          "type": "string"
        },
        "reason": {
          "description": "A human readable description used to define what error has occured\n",
          "type": "string"
        }
      }
    },
    "ImageAnalysis": {
      "description": "The resource definition for a list of vulnerabilities on a image tag\n",
      "type": "object",
      "required": [
        "spec"
      ],
      "allOf": [
        {
          "$ref": "#/definitions/Object"
        }
      ],
      "properties": {
        "spec": {
          "$ref": "#/definitions/ImageAnalysisSpec"
        }
      }
    },
    "ImageAnalysisList": {
      "description": "The resource definition for the results of a image scan on a",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/Object"
        }
      ],
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ImageAnalysis"
          }
        }
      }
    },
    "ImageAnalysisSpec": {
      "description": "The resource specification for a image analysis\n",
      "required": [
        "status",
        "tag"
      ],
      "properties": {
        "features": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ImageFeature"
          }
        },
        "namespace": {
          "description": "The namespace catagory for the layer",
          "type": "string"
        },
        "status": {
          "description": "The status of the image analysis, which can be queued or scanned\n",
          "enum": [
            "scanned",
            "queued"
          ]
        },
        "tag": {
          "$ref": "#/definitions/RepositoryTag"
        }
      }
    },
    "ImageFeature": {
      "description": "A layer feature within the image",
      "type": "object",
      "required": [
        "addedby",
        "format",
        "name",
        "namespace",
        "version"
      ],
      "properties": {
        "addedby": {
          "description": "The layer the feature was added",
          "type": "string"
        },
        "format": {
          "description": "The format of the feature being added",
          "type": "string"
        },
        "name": {
          "description": "The name of the feature which is being added",
          "type": "string"
        },
        "namespace": {
          "description": "An associated namespace to describe the feature",
          "type": "string"
        },
        "version": {
          "description": "An associated version to the feature being added",
          "type": "string"
        },
        "vulnerabilities": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/ImageVulnerability"
          }
        }
      }
    },
    "ImageVulnerability": {
      "description": "Defines the structure for a image vulnerability",
      "type": "object",
      "required": [
        "link",
        "name",
        "severity"
      ],
      "properties": {
        "fixedby": {
          "description": "A potential link or information related to a fix",
          "type": "string"
        },
        "link": {
          "description": "A hyperlink to details on the vulnerability",
          "type": "string"
        },
        "name": {
          "description": "The name of the vulnerability",
          "type": "string"
        },
        "namespace": {
          "description": "The namespace catagory for this vulnerability",
          "type": "string"
        },
        "severity": {
          "description": "The severity severity of the vulnerability",
          "type": "string"
        }
      }
    },
    "Object": {
      "description": "The definition of a object",
      "type": "object",
      "required": [
        "name",
        "namespace"
      ],
      "properties": {
        "name": {
          "description": "A globally unique human readible resource name",
          "type": "string"
        },
        "namespace": {
          "description": "A namespace for the resource, which in this case maps on the organization\n",
          "type": "string"
        }
      }
    },
    "Permission": {
      "description": "Is the definition for a permission on a repository",
      "type": "object",
      "required": [
        "name",
        "permission"
      ],
      "properties": {
        "name": {
          "description": "The identifier for the identity applying the permission to",
          "type": "string"
        },
        "permission": {
          "description": "The level of access to be given to the identify (team, member or robot)\n",
          "type": "string",
          "enum": [
            "admin",
            "none",
            "read",
            "write"
          ]
        }
      }
    },
    "Principal": {
      "type": "string"
    },
    "Repository": {
      "description": "The resource definition for a repository in the registry",
      "type": "object",
      "required": [
        "spec"
      ],
      "allOf": [
        {
          "$ref": "#/definitions/Object"
        }
      ],
      "properties": {
        "spec": {
          "$ref": "#/definitions/RepositorySpec"
        }
      }
    },
    "RepositoryList": {
      "description": "A list of repositories found",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/Object"
        }
      ],
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Repository"
          }
        }
      }
    },
    "RepositorySpec": {
      "description": "The definitions for a repository",
      "type": "object",
      "required": [
        "visibility"
      ],
      "properties": {
        "description": {
          "description": "A description about what the image is used for",
          "type": "string"
        },
        "members": {
          "description": "A list of members whom has access to the repository",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Permission"
          }
        },
        "robots": {
          "description": "A list of robot accounts who access to the repository",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Permission"
          }
        },
        "tags": {
          "description": "A collection of tags associated to the image",
          "type": "array",
          "items": {
            "$ref": "#/definitions/RepositoryTag"
          }
        },
        "teams": {
          "description": "A list of teams which have access to the repository",
          "type": "array",
          "items": {
            "$ref": "#/definitions/Permission"
          }
        },
        "url": {
          "description": "The docker pull url for this image",
          "type": "string"
        },
        "visibility": {
          "description": "The visibility of the repository in the registry",
          "type": "string",
          "enum": [
            "internal",
            "private",
            "public"
          ]
        }
      }
    },
    "RepositoryTag": {
      "description": "The definition for a repository image tag",
      "type": "object",
      "required": [
        "digest",
        "imageId",
        "last_modified",
        "name"
      ],
      "properties": {
        "digest": {
          "description": "Is the image digest for this image",
          "type": "string"
        },
        "imageId": {
          "description": "Is the image id for this image tag",
          "type": "string"
        },
        "last_modified": {
          "description": "The last time the tags was modified",
          "type": "string"
        },
        "name": {
          "description": "Is the image tag name i.e. latest, v0.0.1 etc",
          "type": "string"
        },
        "size": {
          "description": "The size of the image in the repository",
          "type": "integer"
        }
      }
    },
    "Robot": {
      "description": "The resource definition for a robot account",
      "type": "object",
      "required": [
        "spec"
      ],
      "allOf": [
        {
          "$ref": "#/definitions/Object"
        }
      ],
      "properties": {
        "spec": {
          "$ref": "#/definitions/RobotSpec"
        }
      }
    },
    "RobotList": {
      "description": "A list of robot accounts",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/Object"
        }
      ],
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Robot"
          }
        }
      }
    },
    "RobotSpec": {
      "description": "The resource specification of a robot account",
      "type": "object",
      "required": [
        "description"
      ],
      "properties": {
        "description": {
          "description": "A summary of what the robot account is for",
          "type": "string"
        },
        "password": {
          "description": "The password associated to the robot account",
          "type": "string"
        },
        "tags": {
          "description": "A collection of tags associated to the robot account",
          "type": "object",
          "additionalProperties": {
            "type": "string"
          }
        },
        "token": {
          "description": "The token associated to the the robot account",
          "type": "string"
        },
        "username": {
          "description": "The username associated to the robot account",
          "type": "string"
        }
      }
    },
    "Team": {
      "description": "Is the team resources i.e collection of members",
      "type": "object",
      "required": [
        "spec"
      ],
      "allOf": [
        {
          "$ref": "#/definitions/Object"
        }
      ],
      "properties": {
        "spec": {
          "$ref": "#/definitions/TeamSpec"
        }
      }
    },
    "TeamList": {
      "description": "A collection of teams in the organization",
      "type": "object",
      "allOf": [
        {
          "$ref": "#/definitions/Object"
        }
      ],
      "properties": {
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Team"
          }
        }
      }
    },
    "TeamSpec": {
      "description": "Is the specification of the configuration of the resource",
      "type": "object",
      "properties": {
        "members": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    }
  },
  "parameters": {
    "authinfo": {
      "type": "string",
      "description": "An authentication context to speak to the backend of behalf of the Hub\n",
      "name": "X-AuthInfo",
      "in": "header"
    },
    "includeTags": {
      "type": "boolean",
      "description": "Indicates we should include tags in the repositories\n",
      "name": "includeTags",
      "in": "query"
    },
    "limit": {
      "type": "integer",
      "default": 5,
      "description": "Used to limit the results of a query\n",
      "name": "limit",
      "in": "query"
    },
    "name": {
      "type": "string",
      "description": "The name of the repository you are acting upon\n",
      "name": "name",
      "in": "path",
      "required": true
    },
    "namespace": {
      "type": "string",
      "description": "The namespace of the repository\n",
      "name": "namespace",
      "in": "path",
      "required": true
    },
    "repository": {
      "description": "The repository definition we are acting on\n",
      "name": "repository",
      "in": "body",
      "required": true,
      "schema": {
        "$ref": "#/definitions/Repository"
      }
    },
    "robot": {
      "description": "The definition of a robot account within the registry\n",
      "name": "robot",
      "in": "body",
      "required": true,
      "schema": {
        "$ref": "#/definitions/Robot"
      }
    },
    "tag": {
      "type": "string",
      "description": "Used to specify a specific image tag\n",
      "name": "tag",
      "in": "query"
    },
    "team": {
      "description": "The definition of a team within the organization\n",
      "name": "team",
      "in": "body",
      "required": true,
      "schema": {
        "$ref": "#/definitions/Team"
      }
    }
  },
  "responses": {
    "analysis": {
      "description": "The image analysis of the tags",
      "schema": {
        "$ref": "#/definitions/ImageAnalysisList"
      }
    },
    "apierror": {
      "description": "A generic erorr returned by the api",
      "schema": {
        "$ref": "#/definitions/APIError"
      }
    },
    "notfound": {
      "description": "The resource does not exist"
    },
    "repositories": {
      "description": "A collection repositories found in the registry",
      "schema": {
        "$ref": "#/definitions/RepositoryList"
      }
    },
    "repository": {
      "description": "The specification of a repository in the registry",
      "schema": {
        "$ref": "#/definitions/Repository"
      }
    },
    "robot": {
      "description": "Returning the status of a robot account",
      "schema": {
        "$ref": "#/definitions/Robot"
      }
    },
    "robots": {
      "description": "Returning a list of robot accounts",
      "schema": {
        "$ref": "#/definitions/RobotList"
      }
    },
    "team": {
      "description": "The specification of a team in the organization",
      "schema": {
        "$ref": "#/definitions/Team"
      }
    },
    "teams": {
      "description": "A collection teams found in the organization",
      "schema": {
        "$ref": "#/definitions/TeamList"
      }
    }
  },
  "securityDefinitions": {
    "apikey": {
      "type": "apiKey",
      "name": "Authorization",
      "in": "header"
    }
  },
  "security": [
    {
      "apikey": []
    }
  ]
}`))
}
